### ISSUE TITLE
Depends on vulnerable axios dependency

### ISSUE THREAD

**Issue by FabianFrank** [merge-api/merge-node-client#21]
```
# npm audit report

axios  0.8.1 - 1.5.1
Severity: moderate
Axios Cross-Site Request Forgery Vulnerability - https://github.com/advisories/GHSA-wf5p-g6vw-rhxx
No fix available
node_modules/@mergeapi/merge-node-client/node_modules/axios
  @mergeapi/merge-node-client  *
  Depends on vulnerable versions of axios
  node_modules/@mergeapi/merge-node-client

2 moderate severity vulnerabilities
```

**Comment by dsinghvi** [comment]
@FabianFrank  thanks for the issue report; we're going to be releasing a new version of the client that depends on fetch instead!

**Comment by FabianFrank** [comment]
@dsinghvi any update on when that fix will be available?

**Comment by milo-stadion** [comment]
Be great to get this one fixed!

**Comment by dsinghvi** [comment]
This should now be fixed! @FabianFrank @milo-stadion the SDK now relies on `fetch` and works in multiple environments like Cloudflare, Vercel and Node.js.
