### ISSUE TITLE
Standardisation of `fieldMappings`

### ISSUE THREAD

**Issue by hrc-yu** [merge-api/merge-node-client#22]
For the new SDK, the field names have been converted from snake case to camel case. However, I've noticed this translation has not extended to the contents of `fieldMappings` which is now appearing as so in the get employee response from the SDK:

```
 fieldMappings: {
      organization_defined_targets: {},
      linked_account_defined_targets: {}
    }
```

I understand that the internals of `organization_defined_targets` need to be freeform, but wondering if the type could be changed from 

```
fieldMappings?: Record<string, unknown>;
```

to 
```
 fieldMappings?: {
        organizationDefinedTargets: Record<string, {value: unknown}>;
        linkedAccountDefinedTargets: Record<string, {value: unknown}>;
    }
```

Just preference to avoid a mismatch of casing and to introduce some stricter typing.

**Comment by dsinghvi** [comment]
@hrc-yu for some additional context here, when the value of a payload is typed as `unknown` we do not change the casing. The casing is only modified for fields that are explicitly typed and aren't `unknown`. While we could try to scan the unknown payload and modify the keys in the SDK dynamically, the benefit of doing so is unclear if the type is `unknown` anyways.
