### ISSUE TITLE
Fetcher retry interval uses milliseconds instead of seconds

### ISSUE THREAD

**Issue by ismeta** [merge-api/merge-node-client#44]
At least, I assume the intent is seconds :)

[Here](https://github.com/merge-api/merge-node-client/blob/main/src/core/fetcher/Fetcher.ts#L108C48-L108C58) the timeout starts off as `INITIAL_RETRY_DELAY` (`1`), but the `delay` arg for `setTimeout` is based on [milliseconds](https://developer.mozilla.org/en-US/docs/Web/API/Window/setTimeout).

Can this be changed so `INITIAL_RETRY_DELAY` starts at 1000 milliseconds, instead of 1? 1 milli isn't too useful!

I'd also love to be able to configure the initial retry delay myself - some API rate limits may need a far longer wait than 1s and I don't want to get there with a large-n of retries.

**Comment by dsinghvi** [comment]
@ismeta we'll follow up here -- the merge team just needs to bump their TypeScript generator and regenerate the SDK!

**Comment by ismeta** [comment]
Thank you :)

**Comment by ismeta** [comment]
@dsinghvi following up again

**Comment by ismeta** [comment]
@dsinghvi bump!

**Comment by dsinghvi** [comment]
@ismeta this should be fixed in the latest version!
